deploy backend, frontend, and db migration

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -436,6 +436,117 @@ jobs:
           stack-name: "backend-${CIRCLE_WORKFLOW_ID:0:7}"
       - revert-migrations
 
+  smoke-test:
+    docker:
+       - image: cimg/base:stable
+    steps:
+      - checkout
+      - install-aws
+      - install-nodejs
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: Get backend url
+          command: |
+            export API_URL="http://$(tail -n 1 ~/project/.circleci/ansible/inventory.txt):3030"
+            echo "${API_URL}"
+      - run:
+          name: Backend smoke test.
+          command: |
+            export API_URL="http://$(tail -n 1 ~/project/.circleci/ansible/inventory.txt):3030"
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+                exit 0
+            else
+                exit 1
+            fi
+      - run:
+          name: Frontend smoke test.
+          command: |
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            echo ${URL} 
+            if curl -s ${URL} | grep "Welcome"
+            then
+                # Change this to 0 after the job fails
+              exit 0
+            else
+              exit 1
+            fi
+      - clear-bucket
+      - destroy-environment:
+          stack-name: "frontend-${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment:
+          stack-name: "backend-${CIRCLE_WORKFLOW_ID:0:7}"
+      - revert-migrations    
+      - slack_notify    
+
+  cloudfront-update:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - checkout
+      - install-aws
+      - install-nodejs
+      - attach_workspace:
+          at: ~/
+      # - run:
+      #     name: Export Old Workflow ID
+      #     command: |
+      #       export OLD_WORKFLOW_ID=$(aws cloudformation \
+      #                 list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+      #                 --no-paginate --output text)
+      #       echo "Old Workflow ID: $OLD_WORKFLOW_ID"
+      #       $(curl https://keyvalue.immanuel.co/api/KeyVal/UpdateValue/$(cat ~/appkey.txt)/oldWorkflowId/$OLD_WORKFLOW_ID)
+      - run:
+          name: Update cloudfront distribution
+          command: |
+            export OldWorkflowID=$(aws cloudformation \
+            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+            --no-paginate --output text)
+            
+            aws cloudformation deploy \
+            --template-file .circleci/files/cloudfront.yml \
+            --stack-name OldStack \
+            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+            --tags project=udapeople
+
+            aws cloudfront create-invalidation \
+            --distribution-id $DISTRO_ID \
+            --paths "/*"
+
+            curl -k https://kvdb.io/FB4P5zoVABgYfhH8zajZUm/udapeople_old_workflow_id -d "${OldWorkflowID}"
+      - clear-bucket
+      - destroy-environment:
+          stack-name: "frontend-${CIRCLE_WORKFLOW_ID:0:7}"
+      - destroy-environment:
+          stack-name: "backend-${CIRCLE_WORKFLOW_ID:0:7}"
+      - revert-migrations    
+      - slack_notify     
+
+  cleanup:
+      docker:
+        - image: cimg/base:stable
+      steps:
+        - checkout
+        - install-aws
+        - install-nodejs
+        - attach_workspace:
+            at: ~/
+        - run:
+            name: Delete previous stacks and files
+            command: |
+              OldWorkflowID=$(curl --insecure https://kvdb.io/FB4P5zoVABgYfhH8zajZUm/udapeople_old_workflow_id)
+              CurrentWorkflowID=${CIRCLE_WORKFLOW_ID:0:7}
+              
+              echo "Old Workflow ID: $OldWorkflowID"  
+              echo "Current Workflow ID: $CurrentWorkflowID"  
+
+              if [[ "$CurrentWorkflowID" != "$OldWorkflowID"  ]]
+              then
+                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+                aws cloudformation delete-stack --stack-name "backend-${OldWorkflowID}"
+                aws cloudformation delete-stack --stack-name "frontend-${OldWorkflowID}"
+              fi
 
 workflows:
   default:
@@ -465,3 +576,5 @@ workflows:
               only: main
       - configure-infrastructure:
           requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
